### ISSUE TITLE
Should ereject work?

### ISSUE THREAD

**Issue by armarti** [ProtonMail/libsieve-php#31]
Hi PM Team,

I'm not sure if this lib is in production, but it looks (from a quick glance) that this library should be capable of sending an **ereject**, in addition to a **reject**. However in the beta web UI Sieve editor, using **ereject** results in a validation error, and the "Save" button is grayed out and the rule can't be saved.

So, questions:
- is this libsieve-php the Sieve library we're interacting with in the beta web UI?
- is it expected that using **ereject** will cause a validation failure?

Thanks!

**Comment by donataso** [comment]
Hi David,

**ereject** is not currently supported, but you could create a feature request [here](https://protonmail.uservoice.com/forums/284483-feedback).

Thank you for using ProtonMail.

**Comment by bartbutler** [comment]
@armarti the reason ereject is not supported is that due to architectural reasons we aren't able to reject at the SMTP level with Sieve filters. So we could support ereject and simply continue to not reject at the SMTP level but that would remove the difference between reject and ereject (best effort SMTP-level rejection), so that was the reasoning.

**Comment by localjo** [comment]
I have suggested this on UserVoice, if anyone else wants to upvote it: https://protonmail.uservoice.com/forums/284483-protonmail/suggestions/42424525-ereject
